apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
    traefik.enable: "true"
    traefik.http.routers.fastapi.rule: {{ .Values.web.httpPrefix }}'{{ .Release.Namespace }}{{ .Values.web.httpHost }}'{{ .Values.web.httpSufix }}
  labels:
    io.kompose.service: {{ .Release.Namespace }}-web
  name: {{ .Release.Namespace }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Namespace }}-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
        traefik.enable: "true"
        traefik.http.routers.fastapi.rule:  {{ .Values.web.httpPrefix }}'{{ .Release.Namespace }}{{ .Values.web.httpHost }}'{{ .Values.web.httpSufix }}
      labels:
        io.kompose.service: {{ .Release.Namespace }}-web
    spec:
      containers:
      - name: {{ .Release.Namespace }}-web
        image: {{ .Values.web.image.repository }}:{{.Values.web.image.tag}}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.web.service.port }}
          protocol: TCP      
        env:
        - name: DATABASE_URL
          value: postgresql://fastapi_traefik:fastapi_traefik@{{ .Release.Namespace }}-db:5432/fastapi_traefik
      imagePullSecrets: 
      - name: {{ .Values.web.imagePullSecrets.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
    traefik.enable: "true"
    traefik.http.routers.fastapi.rule:  {{ .Values.web.httpPrefix }}'{{ .Release.Namespace }}{{ .Values.web.httpHost }}'{{ .Values.web.httpSufix }}
  labels:
    io.kompose.service: {{ .Release.Namespace }}-web
  name: {{ .Release.Namespace }}-web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: "{{ .Values.web.service.port }}"
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    io.kompose.service: {{ .Release.Namespace }}-web