apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: traefik
    spec:
      containers:
        - image: traefik:v2.9.6
          name: traefik
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/traefik/traefik.toml
              name: traefik-cm0
              subPath: traefik.toml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: traefik.dev.toml
                path: traefik.toml
            name: traefik-cm0
          name: traefik-cm0
