apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
    traefik.enable: "true"
    traefik.http.routers.fastapi.rule: Host(`traefik.seb-cours-datascientest.cloudns.eus`)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
        traefik.enable: "true"
        traefik.http.routers.fastapi.rule: Host(`traefik.seb-cours-datascientest.cloudns.eu`)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            
          env:
            - name: DATABASE_URL
              value: postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
          image: sebdevops06/traefik:latest
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 8000
              protocol: TCP
        #  volumeMounts:
        #    - mountPath: /app
        #      name: web-cm0
      restartPolicy: Always
     # volumes:
     #   - configMap:
     #       name: web-cm0
     #     name: web-cm0
